### ISSUE TITLE
Policy Build is not working

### ISSUE THREAD

**Issue by ansaryansu** [azure-ad-b2c/vscode-extension#23]
![image](https://user-images.githubusercontent.com/3447386/88281684-bd23ec00-cd05-11ea-9607-643347fd841d.png)
![image](https://user-images.githubusercontent.com/3447386/88281762-d9278d80-cd05-11ea-8192-0de6f75b8fbb.png)
![image](https://user-images.githubusercontent.com/3447386/88282101-813d5680-cd06-11ea-8ccf-5b686e55a281.png)

The policy build shows that the policies have successfully exported. But when looking into the policy root folder, no environments are created.

VS Code Version: 1.47.2
azureadb2ctools.aadb2c Version: v1.2.92

From the Extension log file:

[2020-07-23 17:09:15.203] [exthost] [error] [AzureADB2CTools.aadb2c] provider FAILED
[2020-07-23 17:09:15.203] [exthost] [error] Error: Illegal argument, contents must be defined
	at new B (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:440:527)
	at new B (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:429:431)
	at c:\Users\ansary.rd\.vscode\extensions\azureadb2ctools.aadb2c-1.2.92\out\HoverProvider.js:38:28
	at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by DibyodyutiMondal** [comment]
Also facing the same problem

**Comment by ansaryansu** [comment]
I just updated the extension & It's working fine now. Thank you very much for fixing the issue.
